<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Main Test Suite" duration-ms="57808" started-at="2019-01-25T21:42:46Z" finished-at="2019-01-25T21:43:44Z">
    <groups>
    </groups>
    <test name="TestNG Test Group" duration-ms="57808" started-at="2019-01-25T21:42:46Z" finished-at="2019-01-25T21:43:44Z">
      <class name="Testng.improvedtestng">
        <test-method status="PASS" signature="launch()" name="launch" is-config="true" duration-ms="56650" started-at="2019-01-25T21:42:46Z" finished-at="2019-01-25T21:43:43Z">
        </test-method>
        <test-method status="PASS" signature="verifytitle()" name="verifytitle" duration-ms="116" started-at="2019-01-25T21:43:43Z" finished-at="2019-01-25T21:43:43Z">
        </test-method>
        <test-method status="FAIL" signature="verifyurl()" name="verifyurl" duration-ms="170" started-at="2019-01-25T21:43:43Z" finished-at="2019-01-25T21:43:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<edureka> but was:<https://www.edureka.co/>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<edureka> but was:<https://www.edureka.co/>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:480)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at Testng.improvedtestng.verifyurl(improvedtestng.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at org.testng.TestNG.privateMain(TestNG.java:1182)
	at org.testng.TestNG.main(TestNG.java:1146)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="close()" name="close" is-config="true" duration-ms="846" started-at="2019-01-25T21:43:43Z" finished-at="2019-01-25T21:43:44Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
